# Generated by cucumber-sinatra. (Sun May 08 09:24:06 -0430 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'dashboard.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Sinatra::Application

class Sinatra::ApplicationWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Sinatra::ApplicationWorld.new
end
